sudo: false

os: osx
osx_image: xcode9.2
compiler:
  - clang
script:
  - brew tap thesriram/aws-sam-cli
  - brew install --build-bottle aws-sam-cli
  - brew bottle --no-rebuild --json --root-url=https://github.com/TheSriram/homebrew-aws-sam-cli/releases/download/v0.15.0/ aws-sam-cli
before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - 'echo ''Deploying files to Github: ''$RELEASE_FILES'
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $RELEASE_FILES
  skip_cleanup: true
  on:
    all_branches: true
    repo: TheSriram/homebrew-aws-sam-cli
  overwrite: true
