sudo: false

os: osx
osx_image: xcode9.2
compiler:
  - clang
before_install:
  - brew update
script:
  - git fetch --tags
  - git checkout $(git describe --abbrev=0 --tags)
  - git log
  - brew tap thesriram/aws-sam-cli
  - brew install --build-from-source --build-bottle Formula/aws-sam-cli.rb
  - brew bottle aws-sam-cli
before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - 'echo ''Deploying files to Github: ''$RELEASE_FILES'
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $RELEASE_FILES
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: TheSriram/homebrew-aws-sam-cli
  overwrite: true
