sudo: false

os: osx
osx_image: xcode9.2
compiler:
  - clang
script:
  - brew tap thesriram/aws-sam-cli
  - brew install --build-bottle aws-sam-cli
  - brew bottle --no-rebuild --json --root-url=https://github.com/TheSriram/homebrew-aws-sam-cli/releases/download/v0.15.0/ aws-sam-cli
before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - echo 'Sanity check of bottle'
  - brew uninstall aws-sam-cli
  - brew install $RELEASE_FILES
  - sam --version
  - echo 'Sanity check passed!'
  - echo 'Deploying files to S3'
  - mkdir release_artifacts
  - ls *.bottle.tar.gz | xargs -I{} cp {} release_artifacts/
  - 'echo ''Deploying files to S3: ''$RELEASE_FILES'
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: aws-sam-cli-sriram-bottles
  acl: bucket_owner_full_control
  local_dir: release_artifacts/
  on:
    branch: release
    repo: TheSriram/homebrew-aws-sam-cli
