sudo: false

os: osx
osx_image: xcode9.2
compiler:
  - clang
branches:
  only:
    - master
before_install:
  - brew update
script:
  - brew tap aws/tap
  - brew install --build-from-source --build-bottle Formula/aws-sam-cli.rb
  - brew bottle aws-sam-cli
before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - 'echo ''Deploying files to Github: ''$RELEASE_FILES'
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $RELEASE_FILES
  skip_cleanup: true
  on:
    repo: TheSriram/homebrew-aws-sam-cli
  overwrite: true
