sudo: false

os:
  - osx
compiler:
  - clang
branches:
  only:
    - master
before_install:
  - brew update
script:
  - brew tap thesriram/aws-sam-cli
  - brew install --build-from-source --build-bottle aws-sam-cli
  - brew bottle aws-sam-cli
before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - 'echo ''Deploying files to Github: ''$RELEASE_FILES'
deploy:
  provider: releases
  api_key:
    secure: "MFaU7+1gla8AP51w0WBNbhtKIMTiu8okk0UFoeaAT1EZzRm43qIPMYUBybxTx/nfs06MOWS9x+LWQ/3rPuvXkpSHmYJLW1MJW4JrLZYSbUFAY/HMqnr2ypDVUBwzwOxGBX+6qiJpXZpO9d9R7FyM9lN1Z0fDk3aMMV5+TFizzZgCpTUbbP+grOXrIpMsYcxqmOI6brKaPs340EudV4FNPVUWx8qfBkeqKVqIVTvivlSJLqFwaRwl3Opif8H/X1Bx0mDCP07EEUlWjyv6wA5gsS9VmhfhAP8kvzvnIhmhYCwnDIZV73zQFzzTOsDAD4CBTEsMIA4mCngc6iAUz9JYPhgB9KE36nX8fBgpa4cIu/71xsgg/vvC99S5ShpYTOZ/BhMjzdf/JyWKg8clBclJabLL3HfdTuXA+kMIqdsxgr7GM0PwnQn3yihNBLebWyZF4YT1/6NWTH/wcNxhfciJjUcDQGxnF1dlAgrVnyee+R+q8fX2kyoVXgV2kDTtj+HBU4z4pzFX51k4bbPVvbFMPfRxlE7lvGxVfizqGHewK6D2+TBdF13rtpkbOU8CR2xX8Q9WTK2iTZZSj4gbLjfB415x4IN/clKMP0iLVq1E+toRrU48eSElfgZncdSHfgxRk8CgiO1eZI0EfxgfMP/OdtmPVJR1To7evsVzW06QRzo="
  file: "{$RELEASE_FILES}"
  skip_cleanup: true
  on:
    repo: TheSriram/homebrew-aws-sam-cli
  overwrite: true
